[package]
name = "finch"
version = "0.4.3"

[dependencies]
base64 = "0.9.0"
structopt = "0.2.7"
walkdir = "2.1.4"
image = "0.18.0"
reqwest = "0.8.5"
serde = "1.0.43"
serde_derive = "1.0.43"
serde_json = "1.0"
rayon = "1.0.1"
log = "0.4.2"
simplelog = "0.5.2"
failure = "0.1.1"